<!DOCTYPE html>
<html lang="ko">

<head>
    <?php include("../inc/head.php") ?>
    <link rel="stylesheet" type="text/css" href="../css/Rogowski_Coils/Ruggedized_Clamp-on_Rogowski_Coils.css">
</head>

<body>
    <!--<h1>0</h1>-->
    <!-- header -->
    <?php include("../inc/header.php") ?>
    <!-- //header -->
    <!-- container -->
    <container id="container" class="depth_03 rgdz_ci">
        <h1 class="blind">container Area</h1>
        <!--<div class="spl_visual">
            <div class="visual_box">
                <div class="visual_txt">
                    <p>Rigid Rogowski Coils</p>
                    <span></span>
                </div>
            </div>
            <div class="prllgr"></div>
            <div class="spl_txt">
                <p>Taehwatrans rigid Rogowski coils are an air cored (non-magnetic) toroidal windings positioned round the conductor. An alternating magnetic field generated by the current in the primary conductor induces a voltage in the coil. Thanks to low inductance and its non-magnetic core, Rogowski coils have the output voltage linearity proportional to the frequency increase and the output of the coil does not saturate for a high primary current more than 1kA and, leading to achieve a great accuracy on high current range. Traditional current transformers for high current measurement are bulky and heavy so that they seriously limit the design flexibility of systems. However, Rogowski coils with compact and light weight design, can provide great advantage for system design to be smarter and more compact.</p>
            </div>
        </div>-->
        <div class="serch_wrap">
            <div class="serch_box tab-content">
                <div class="select_box first-child">
                    <form action="#" method="get" class="select_form">
                        <fieldset>
                            <legend class="blind">제품군</legend>
                            <p>
                                <select name="select" id="select" class="select" title="선택해 주세요.">
                                    <option value="">Products</option>
                                    <option value="#">Solid-Leadwire Rogowski Coils</option>
                                    <option value="#">Flexible Rogowski coils</option>
                                    <option value="#" selected="select">Ruggedized Clamp-on Rogowski coils</option>
                                </select>
                            </p>
                        </fieldset>
                    </form>
                </div>
                <div class="select_box">
                    <form action="#" method="get" class="select_form">
                        <fieldset>
                            <legend class="blind">카테고리</legend>
                            <p>
                                <select name="select" id="select" class="select" title="선택해 주세요.">
                                    <option value="" selected="select">카테고리</option>
                                    <option value="#">옥외용 분할전류센서</option>
                                    <option value="#">프렉서블 코일</option>
                                    <option value="#">에너지 하비스트 계전용 센서</option>
                                    <option value="#">로고스키코일 센서</option>
                                </select>
                            </p>
                        </fieldset>
                    </form>
                </div>
                <div class="select_box">
                    <form action="#" method="get" class="select_form">
                        <fieldset>
                            <legend class="blind">시리즈</legend>
                            <p>
                                <select name="select" id="select" class="select" title="선택해 주세요.">
                                    <option value="" selected="select">시리즈</option>
                                    <option value="#">옥외용 분할전류센서</option>
                                    <option value="#">프렉서블 코일</option>
                                    <option value="#">에너지 하비스트 계전용 센서</option>
                                    <option value="#">로고스키코일 센서</option>
                                </select>
                            </p>
                        </fieldset>
                    </form>
                </div>
                <div class="search">
                    <form action="#" method="get" class="serch_bar">
                        <fieldset>
                            <legend class="blind">검색</legend>
                            <p>
                                <span class="board-sch-keyword-1">
                                    <input type="text" name="board-sch-keyword" id="board-sch-keyword" title="게시판 검색어" value="" placeholder="모델명을 입력해 주세요">
                                </span>
                            </p>
                        </fieldset>
                    </form>
                </div>
                <div class="sc_button">
                    <button>검색</button>
                </div>
            </div>
        </div>
        <div class="nav_wrap">
            <nav>
                <ul class="cf">
                    <li class="nv_m_01"><a href="#">Products</a></li>
                    <li class="nv_m_02"><a href="#">Features</a></li>
                    <li class="nv_m_03"><a href="#">Drawing</a></li>
                    <li class="nv_m_04"><a href="#">Dimension</a></li>
                    <li class="nv_m_05"><a href="#">Inquiry</a></li>
                    <li class="bgc_00304a"><a href="#">FAQ</a></li>
                </ul>
            </nav>
        </div>
        <div class="prdt_dscrt">
            <div class="dscrt_txt_wrap">
                <div class="dscrt_txt_box">
                    <h2>Ruggedized Clamp-on Rogowski coils</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere atque, nesciunt, laudantium, similique porro alias maxime quod ea, minus est quo sit error quos amet rerum aliquid voluptate placeat magni.</p>
                    <a href="#">Enquire</a>
                </div>
            </div>
        </div>
        <!------------------------------------------------------------------------------------------------------------->
        
        <div class="od_spl_title">
            <p>Taehwatrans rigid Rogowski coils are an air cored (non-magnetic) toroidal windings positioned round the conductor. An alternating magnetic field generated by the current in the primary conductor induces a voltage in the coil. Thanks to low inductance and its non-magnetic core, Rogowski coils have the output voltage linearity proportional to the frequency increase and the output of the coil does not saturate for a high primary current more than 1kA and, leading to achieve a great accuracy on high current range. Traditional current transformers for high current measurement are bulky and heavy so that they seriously limit the design flexibility of systems. However, Rogowski coils with compact and light weight design, can provide great advantage for system design to be smarter and more compact.</p>
        </div>
        
        <div class="od_spl_title">
            <span></span>
            <h2>Rogowski Coil Sensors</h2>
            <div class="od_spl_imgBox">
                <img src="../img/Rogowski_Coils/UZDJ0919489032.jpg" alt="Electrical Properties">
            </div>
            <p>High Current &amp; High Frequency Measurement Rogowski coil Sensor</p>
        </div>

        <div class="dep03_introduce_txt">
            <p style="margin-top: 80px;"><strong>Rogowski coil Sensors</strong> are applied to electrical devices that measure up to thousands of amp AC (alternating current) for power meters, energy sub meters, condition monitoring, power quality monitoring as well as distributed measurement systems and current spike detection. No iron or other metal core is involved in the construction. What is critical is the diameter of the coil, the winding density and the rigidity of the winding, which help to preserve immunity to the various external fields</p>
            <p><strong>Rogowski Coil Sensors Application</strong><br><br>
                - Smart Recloser on Distribution Line<br>
                - Electronic Sectionalizer<br>
                - Smart Grid Application<br>
                - High Current Energy Meters &amp; Protection Relay<br>
                - Harmonics Measurement Sensors<br>
                - Air Circuit Breakers &amp; Smart Reclosers<br>
                - Gas Insulation Switch Gear<br>
                - AC Component Fault Detector out of DC Current<br>
                - High Frequency High Current Measurements<br>
                - High Current Welding Machines<br><br><br>
                <strong>Rogowski Coil Sensors General Features</strong><br><br>
                - Compliant to IEC 61869-2<br>
                - Perfect Immunity to DC external magnetic field<br>
                - High Current Coverage without Saturation<br>
                - Operating Frequency unto 1MHz or 3MHz<br>
                - Intrinsic Frequency Linearity<br>
                - High Potential Voltage: 4kV per min<br>
                - RoHS Compliant<br><br><br>
                <strong>Rogowski Coil Sensors Test Conditions:</strong><br><br>
                - Mutual Inductance Value Applied upon the Primary 100A<br>
                - Max Stray Noise Output Voltage (Vo) based on External Magnetic Field 0.5mT<br>
                - Burden Resister: 1MΩ<br><br><br>
            </p>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>Electrical Properties ( I )</h2>
            <div class="od_spl_imgBox">
                <img src="../img/Rogowski_Coils/MJAO0936602074.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
            <p>High Current &amp; High Frequency Measurement Rogowski coil Sensor</p>
        </div>
        <div class="od_spl_title">
            <!--<span></span>-->
            <h2>Specification</h2>
            <div class="table_wrap">
                <table class="spec_table">
                    <thead>
                        <tr>
                            <th class="bdl_n">Model NO</th>
                            <th>DCR(Ω)<br>±6%</th>
                            <th>Rated<br> Current(A)</th>
                            <th>Max<br>Current(KA)</th>
                            <th>Self<br>Current(KA)</th>
                            <th>Mutual<br>Inductance</th>
                            <th>Max Stray<br>Noise Vo</th>
                            <th>Max Multual Inductance Erro(%)</th>
                            <th>Output Voltage at 100A</th>
                            <th class="bdr_n">Instant Peak Amp(KA)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>TR77V/L</td>
                            <td>100Ω</td>
                            <td rowspan="6" class="last">1000Ω</td>
                            <td>10kA</td>
                            <td>0.7mH</td>
                            <td>0.69µH</td>
                            <td>1.3mV</td>
                            <td>0.60%</td>
                            <td>21.6mV</td>
                            <td>64kA</td>
                        </tr>
                        <tr>
                            <td>TR71V/L</td>
                            <td>181Ω</td>
                            <td>9kA</td>
                            <td>7.6mH</td>
                            <td>3.25µH</td>
                            <td>0.3mV</td>
                            <td>0.03%</td>
                            <td>102.2mV</td>
                            <td>54kA</td>
                        </tr>
                        <tr>
                            <td>TR71VA</td>
                            <td>13.5Ω</td>
                            <td>13kA</td>
                            <td>0.4mH</td>
                            <td>0.80µH</td>
                            <td>0.3mV</td>
                            <td>0.12%</td>
                            <td>25.0mV</td>
                            <td>81kA</td>
                        </tr>
                        <tr>
                            <td>TR10VSH<br>TR10LSH<br>TR10LSC</td>
                            <td>173Ω</td>
                            <td>6kA</td>
                            <td>5.8mH</td>
                            <td>2.13µH</td>
                            <td>0.6mV</td>
                            <td>0.09%</td>
                            <td>66.9mV</td>
                            <td>39kA</td>
                        </tr>
                        <tr>
                            <td>TR9L</td>
                            <td>200Ω</td>
                            <td>6kA</td>
                            <td>20.9mH</td>
                            <td>4.48µH</td>
                            <td>4.0mV</td>
                            <td>0.28%</td>
                            <td>140.8mV</td>
                            <td>40kA</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="tqp_srs_wrap">
            <div id="tqp_srs_wrap" class="tqp_srs_box srs_bx_01 cf">
                <div class="tqp_srs_txt">
                    <div class="srs_txt_title src_title_01 cf">
                        <h4>Drawing</h4>
                        <span></span>
                    </div>
                    <div class="srs_txt_p srs_txt_01">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus suscipit ab odio. Dolorem consequatur minus est temporibus libero perferendis quis veniam? Quae consectetur labore animi reprehenderit. Qui et dignissimos, ipsa.</p>
                    </div>
                </div>
                <div class="tqp_srs_img srs_img_01">
                    <img src="../img/Rogowski_Coils/Electrical Properties-Drawing.png" alt="Electrical Properties-Drawing">
                </div>
            </div>
        </div>
        <div class="od_spl_title">
            <!--<span></span>-->
            <h2>Dimension</h2>
            <div class="table_wrap">
                <table class="spec_table">
                    <thead>
                        <tr>
                            <th class="bdl_n">Model NO</th>
                            <th>A(min)</th>
                            <th>B(max)</th>
                            <th>C(max)</th>
                            <th>D(max)</th>
                            <th>E(±0.3)</th>
                            <th>F(±0.3)</th>
                            <th>G(±0.5)</th>
                            <th class="bdr_n">H(±0.3)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>TR77V</td>
                            <td>6.8</td>
                            <td>25.0</td>
                            <td>11.0</td>
                            <td>23.5</td>
                            <td>15.1</td>
                            <td>19.1</td>
                            <td>3.0</td>
                            <td>9.1</td>
                        </tr>
                        <tr>
                            <td>TR77L</td>
                            <td>6.9</td>
                            <td>23.6</td>
                            <td>11.0</td>
                            <td>26.8</td>
                            <td>7.1</td>
                            <td>71.0</td>
                            <td>3.0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>TR71V</td>
                            <td>8.9</td>
                            <td>27.5</td>
                            <td>17.0</td>
                            <td>25.3</td>
                            <td>15.1</td>
                            <td>19.1</td>
                            <td>3.0</td>
                            <td>15.1</td>
                        </tr>
                        <tr>
                            <td>TR71L</td>
                            <td>8.9</td>
                            <td>24.8</td>
                            <td>17.0</td>
                            <td>28.4</td>
                            <td>7.6</td>
                            <td>65.0</td>
                            <td>3.0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>TR71VA</td>
                            <td>8.9</td>
                            <td>27.7</td>
                            <td>20.3</td>
                            <td>25.3</td>
                            <td>15.1</td>
                            <td>9.0</td>
                            <td>3.0</td>
                            <td>4.0</td>
                        </tr>
                        <tr>
                            <td>TR10VSH</td>
                            <td>12.9</td>
                            <td>39.3</td>
                            <td>14.0</td>
                            <td>38.0</td>
                            <td>25.2</td>
                            <td>32.8</td>
                            <td>3.0</td>
                            <td>12.1</td>
                        </tr>
                        <tr>
                            <td>TR10LSH</td>
                            <td>12.9</td>
                            <td>37.5</td>
                            <td>14.0</td>
                            <td>41.3</td>
                            <td>10.3</td>
                            <td>240.0</td>
                            <td>5.0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>TR10LSC</td>
                            <td>12.9</td>
                            <td>37.5</td>
                            <td>14.0</td>
                            <td>46.8</td>
                            <td>14.9</td>
                            <td>381.0</td>
                            <td>5.0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>TR9L</td>
                            <td>19.6</td>
                            <td>48.2</td>
                            <td>19.2</td>
                            <td>52.0</td>
                            <td>13.2</td>
                            <td>270.0</td>
                            <td>5.0</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>Electrical Properties ( II )</h2>
            <div class="od_spl_imgBox">
                <img src="../img/Rogowski_Coils/UZDJ0919489032.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
            <p>High Current &amp; High Frequency Measurement Rogowski coil Sensor</p>
        </div>
        <div class="od_spl_title">
            <!--<span></span>-->
            <h2>Specification</h2>
            <div class="table_wrap">
                <div class="table_wrap">
                    <table class="spec_table">
                        <thead>
                            <tr>
                                <th class="bdl_n">Model NO</th>
                                <th>Current Rating(A)</th>
                                <th>Primary Current</th>
                                <th>Output V at Primary</th>
                                <th>Max Current(kA)</th>
                                <th>Self Inductance</th>
                                <th>Mutual Inductance</th>
                                <th>Max Stray Noise Voltage</th>
                                <th class="bdr_n">Max Mutual Inductance Error(%)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>TR1L</td>
                                <td>630A</td>
                                <td>63A</td>
                                <td rowspan="4">16.97mV</td>
                                <td>55kA</td>
                                <td>1.72mH</td>
                                <td>0.856µ</td>
                                <td rowspan="9" class="last">0.3mV</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR2L</td>
                                <td>1000A</td>
                                <td>100A</td>
                                <td>44kA</td>
                                <td>0.69mH</td>
                                <td>0.54µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR3L</td>
                                <td>1250A</td>
                                <td>125A</td>
                                <td>51kA</td>
                                <td>0.43mH</td>
                                <td>0.43µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR4L</td>
                                <td>1600A</td>
                                <td>160A</td>
                                <td>60kA</td>
                                <td>0.26mH</td>
                                <td>0.34µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TRLS</td>
                                <td>1000A</td>
                                <td>100A</td>
                                <td>10.1mV</td>
                                <td>55kA</td>
                                <td>0.69mH</td>
                                <td>0.32µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR5L</td>
                                <td>2000A</td>
                                <td>200A</td>
                                <td rowspan="4" class="last">16.97mV</td>
                                <td>90kA</td>
                                <td>0.32mH</td>
                                <td>0.27µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR6L</td>
                                <td>2500A</td>
                                <td>250A</td>
                                <td>120kA</td>
                                <td>0.22mH</td>
                                <td>0.22µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR7L</td>
                                <td>3200A</td>
                                <td>320A</td>
                                <td>120kA</td>
                                <td>0.13mH</td>
                                <td>0.17µ</td>
                                <td>0.18%</td>
                            </tr>
                            <tr>
                                <td>TR8L</td>
                                <td>4000A</td>
                                <td>400A</td>
                                <td>90kA</td>
                                <td>0.33mH</td>
                                <td>0.14µ</td>
                                <td>0.18%</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="tqp_srs_wrap">
            <div id="tqp_srs_wrap" class="tqp_srs_box srs_bx_01 cf">
                <div class="tqp_srs_txt">
                    <div class="srs_txt_title src_title_01 cf">
                        <h4>Drawing</h4>
                        <span></span>
                    </div>
                    <div class="srs_txt_p srs_txt_01">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus suscipit ab odio. Dolorem consequatur minus est temporibus libero perferendis quis veniam? Quae consectetur labore animi reprehenderit. Qui et dignissimos, ipsa.</p>
                    </div>
                </div>
                <div class="tqp_srs_img srs_img_01">
                    <img src="../img/Rogowski_Coils/Electrical-Properties2-graph-.png" alt="Electrical Properties-Drawing">
                </div>
            </div>
        </div>
        <div class="od_spl_title">
            <!--<span></span>-->
            <h2>Dimension</h2>
            <div class="table_wrap">
                <table class="spec_table">
                    <thead>
                        <tr>
                            <th>Model NO</th>
                            <th>A(min)</th>
                            <th>B(max)</th>
                            <th>B'(max)</th>
                            <th>C(max)</th>
                            <th>D(max)</th>
                            <th>E(max)</th>
                            <th>F(±7)</th>
                            <th>G(±1)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>TR1L<br>TR2L<br>TR3L<br>TR4L</td>
                            <td>53.0</td>
                            <td>75.0</td>
                            <td>48.9</td>
                            <td>12.5</td>
                            <td>76.5</td>
                            <td>31.5</td>
                            <td>300.0</td>
                            <td>5.0</td>
                        </tr>
                        <tr>
                            <td>TRLS</td>
                            <td>50.6</td>
                            <td>64.0</td>
                            <td>10.9</td>
                            <td>7.5</td>
                            <td>24.7</td>
                            <td>16.2</td>
                            <td>300.0</td>
                            <td>5.0</td>
                        </tr>
                        <tr>
                            <td>TR5L<br>TR6L<br>TR7L<br>TR8L</td>
                            <td>98.0</td>
                            <td>119.0</td>
                            <td>54.4</td>
                            <td>11.0</td>
                            <td>76.0</td>
                            <td>31.5</td>
                            <td>300.0</td>
                            <td>5.0</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>Self Powered (Energy Harvesting) Rogowski Sensors</h2>
            <div class="od_spl_imgBox">
                <img src="../img/Rogowski_Coils/Energy Harvesting and Measurement Sensor.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
            <p>Energy Harvesting &amp; Measurement Sensor</p>
        </div>
        <div class="tqp_srs_wrap">
            <div id="tqp_srs_wrap" class="tqp_srs_box srs_bx_01 cf">
                <div class="tqp_srs_txt">
                    <div class="srs_txt_title src_title_01 cf">
                        <h4>Drawing</h4>
                        <span></span>
                    </div>
                    <div class="srs_txt_p srs_txt_01">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus suscipit ab odio. Dolorem consequatur minus est temporibus libero perferendis quis veniam? Quae consectetur labore animi reprehenderit. Qui et dignissimos, ipsa.</p>
                    </div>
                </div>
                <div class="tqp_srs_img srs_img_01">
                    <img src="../img/Rogowski_Coils/Self-Powered-Energy-Harvesting-graph.png" alt="Electrical Properties-Drawing">
                </div>
            </div>
        </div>

        <div class="od_spl_title">
            <!--<span></span>-->
            <h2>Dimension</h2>
            <div class="table_wrap">
                <table class="spec_table">
                    <thead>
                        <tr>
                            <th class="bdl_n">A(min)</th>
                            <th>A'(max)</th>
                            <th>B(max)</th>
                            <th>C(max)</th>
                            <th>D(max)</th>
                            <th>F(±3.0)</th>
                            <th class="bdr_n">G(±1.0)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>46.3</td>
                            <td>10.2</td>
                            <td>73.3</td>
                            <td>33.2/td&gt;
                            </td>
                            <td>51.3</td>
                            <td>150</td>
                            <td>5.0</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="od_spl_title">
            <!--<span></span>-->
            <h2>Electrical Properties</h2>
            <div class="table_wrap">
                <table class="spec_table">
                    <thead>
                        <tr>
                            <th class="bdl_n">Harvesting Power</th>
                            <th>Rating</th>
                            <th>Output</th>
                            <th>Self Inductance</th>
                            <th>Mutual Inductance</th>
                            <th class="bdr_n">Max Mu Error</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>min 3Watt</td>
                            <td>1000A</td>
                            <td>0.1mV/A</td>
                            <td>0.69mH</td>
                            <td>0.32µH</td>
                            <td>0.30%</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="od_spl_title">
            <span></span>
            <h2>Electrical Property &amp; Dimension</h2>
        </div>
        <div id="spcfct_wrap" class="spcfct_wrap">
            <div class="spcfct_box">
                <div class="tabs">
                    <div class="tabs-header">
                        <ul class="nav nav-tabs" role="tablist">
                            <div class="border"></div>
                            <div class="nav_border"></div>
                            <li class="active"><a href="#tab-1" tab-id="1" ripple="ripple" ripple-color="#FFF">Clamp-on Rogowski coils </a></li>
                            <li><a href="#tab-2" tab-id="2" ripple="ripple" ripple-color="#FFF">Clamp-on Rogowski coils with Voltage Screw</a></li>
                        </ul>
                    </div>
                    <button class="tab_btn tab_btn_left"></button>
                    <button class="tab_btn tab_btn_right"></button>
                    <div class="tabs-content">
                        <div tab-id="1" class="tab active">
                            <p style="margin: 10px 0;">Specification</p>
                            <table border="1">
                                <caption class="blind">Specification Spec</caption>
                                <thead></thead>
                                <tbody>
                                    <tr>
                                        <th class="table_head">Model No</th>
                                        <th class="table_head">A(min)</th>
                                        <th class="table_head">B(max)</th>
                                        <th class="table_head">C(max)</th>
                                        <th class="table_head">D(max)</th>
                                    </tr>
                                    <tr>
                                        <td>TSR35L/C</td>
                                        <td>35.0(1.378")</td>
                                        <td>83.0(3.268")</td>
                                        <td>20.9(0.823")</td>
                                        <td>99.5(3.917")</td>
                                    </tr>
                                    <tr>
                                        <td>TSR115L/C</td>
                                        <td>114.5(4.508")</td>
                                        <td>151.2(5.953")</td>
                                        <td>22.4(0.882")</td>
                                        <td>173.0(6.811")</td>
                                    </tr>
                                    <tr>
                                        <td>TSR145L/C</td>
                                        <td>145.0(5.709")</td>
                                        <td>190.0(7.480")</td>
                                        <td>22.5(0.886")</td>
                                        <td>210.0(8.268")</td>
                                    </tr>
                                </tbody>
                            </table>
                            <p style="margin: 10px 0;">Electrical Property</p>
                            <table border="1">
                                <caption class="blind">Electrical Property</caption>
                                <thead></thead>
                                <tbody>
                                    <tr>
                                        <th class="table_head">Accuracy Class<br>(IEC61869-2)</th>
                                        <th class="table_head">"Class 1.0<br>(Reading Accuracy)"</th>
                                        <th class="table_head">Max Short<br>Circuit Current</th>
                                        <th class="table_head">40kA @RL 1MΩ</th>
                                    </tr>
                                    <tr>
                                        <td>Nominal Measurement Current</td>
                                        <td>5A - 6000A</td>
                                        <td>Operating Voltage</td>
                                        <td>a.c. 600V</td>
                                    </tr>
                                    <tr>
                                        <td>Output Voltage @1000A</td>
                                        <td>"90mV ± 5%(60Hz)<br>75mV ± 5%(50Hz)"</td>
                                        <td>Hi-Potential Voltage(per min.)</td>
                                        <td>a.c. 25kV</td>
                                    </tr>
                                    <tr>
                                        <td>Phase Displacement</td>
                                        <td>0.05° (Degree)</td>
                                        <td>IP Rating &amp; UV Resistance</td>
                                        <td>IP66 &amp; UV Resistive</td>
                                    </tr>
                                    <tr>
                                        <td>Positioning Error (0° ~ 360°)</td>
                                        <td>Avr.± 1.0% (max. 1.5%)</td>
                                        <td>Ambient Operating Temp.</td>
                                        <td>40°C ~ +70°C</td>
                                    </tr>
                                    <tr>
                                        <td>Mutual Inductance</td>
                                        <td>239nH / 60Hz</td>
                                        <td>Storage Temperature</td>
                                        <td>-40°C ~ +80°C</td>
                                    </tr>
                                    <tr>
                                        <td>Max External Stray<br>Mutual Inductance Error @0.5mT</td>
                                        <td>"≤0.15%(1000A)≤1.5%(100A)"</td>
                                        <td>Cable</td>
                                        <td>24AWG, 600V</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div tab-id="2" class="tab">
                            <p style="margin: 10px 0;">Specification</p>
                            <table border="1">
                                <caption class="blind">Specification Spec</caption>
                                <thead></thead>
                                <tbody>
                                    <tr>
                                        <th class="table_head">A(min)</th>
                                        <th class="table_head">B(max)</th>
                                        <th class="table_head">C(max)</th>
                                        <th class="table_head">D(max)</th>
                                        <th class="table_head">F(±5)</th>
                                        <th class="table_head">F'(±3)</th>
                                        <th class="table_head">G(±1)</th>
                                    </tr>
                                    <tr>
                                        <td>26</td>
                                        <td>80.3</td>
                                        <td>28</td>
                                        <td>80.6</td>
                                        <td>600</td>
                                        <td>40</td>
                                        <td>10</td>
                                    </tr>
                                    <tr>
                                        <td>1.024"</td>
                                        <td>3.161"</td>
                                        <td>1.102"</td>
                                        <td>3.173"</td>
                                        <td>23.622"</td>
                                        <td>1.575"</td>
                                        <td>0.394"</td>
                                    </tr>
                                </tbody>
                            </table>
                            <p style="margin: 10px 0;">Electrical Property</p>
                            <table border="1">
                                <caption class="blind">Electrical Property</caption>
                                <thead></thead>
                                <tbody>
                                    <tr>
                                        <th class="table_head">Accuracy Class<br>(IEC61869-2)</th>
                                        <th class="table_head">Class 1.0<br>(Reading Accuracy)"</th>
                                        <th class="table_head">Hi-Potential Voltage</th>
                                        <th class="table_head">a.c. 15kV/ 1min.</th>
                                    </tr>
                                    <tr>
                                        <td>Nominal Measurement Current</td>
                                        <td>5A - 6000A</td>
                                        <td>Max Current @1MΩ</td>
                                        <td>400,000A</td>
                                    </tr>
                                    <tr>
                                        <td>Output Voltage @1000A</td>
                                        <td>90mV ± 6%(60Hz)</td>
                                        <td>Max External Stray<br>Mutual Inductance Error @0.5mT</td>
                                        <td>"≤0.15%(1000A)<br>≤1.5%(100A)</td>
                                    </tr>
                                    <tr>
                                        <td>Phase Displacement</td>
                                        <td>0.05° (Degree)</td>
                                        <td>Ambient Operating Temp</td>
                                        <td>40°C ~ +70°C</td>
                                    </tr>
                                    <tr>
                                        <td>Mutual Inductance @ 60Hz</td>
                                        <td>239nH</td>
                                        <td>Storage Temperature</td>
                                        <td>40°C ~ +80°C</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <link rel="stylesheet" type="text/css" href="../css/jquery.scrolling-tabs.css">
                <script type="text/javascript" src="../js/jquery.scrolling-tabs.js"></script>
            </div>
        </div>
        <div class="od_spl_title tt_w_l faq_title">
            <span></span>
            <h2>Inquiry</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore nihil excepturi vitae doloribus, nostrum ratione nesciunt, totam porro distinctio esse voluptates iusto sed perspiciatis commodi accusantium voluptatem doloremque.</p>
            <a href="/index.php">Contacts</a>
        </div>


        <!------------------------------------------------------------------------------------------------------------->
        <!--
        <div class="od_spl_title">
            <h2>Electrical Property &amp; Dimension</h2>
            <span></span>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>Flexible coil &amp; Clamp-On Coil Sensors</h2>
            <div class="od_spl_imgBox">
                <img src="../img/Rogowski_Coils/MJAO0936602074.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
            <p>Supreme Accuracy Rogowski Coils up to accuracy class 0.5High Frequency Monitoring Rogowski Coils up to 1MHz -3dB Clamp-on Rogowski Coils with Voltage Measurement Screw</p>
            <div style="margin-top: 80px;">
                <p><strong>Engineering Profile</strong><br><br>
                    - Flexible &amp; Clamp-on Rogowski Coils are applied to varieties of electrical devices<br>
                    - that measure up to thousands of Amp ac (alternating current) and hundreds thousand<br>
                    - frequency in high accuracy (0.5 or 1.0 class) in the field of Pole-top &amp; Pad mount transformer monitoring,<br>
                    - Sub-station SCADA system, Distribution line measurement, High frequency measurement, Arc fault detection,<br>
                    - and Power quality monitoring.<br>
                    - The reading error meets the metering class 0.5 (or 1.0) along with excellent positioning error.<br><br><br>
                    <strong>Detailed Application</strong><br><br>
                    - Utilities Pole Probe Monitoring &amp; Measurement<br>
                    - Power Distribution Line Monitoring<br>
                    - Current Balance Monitoring<br>
                    - Monitoring &amp; Control of SCADA system for Power &amp; Sub-Station<br>
                    - Overhead / Underground Fault Detector<br>
                    - Arc fault detection<br>
                    - Up to 1MHz high frequency measurement in -3dB (Normally 100KHz - 450KHz)<br>
                    - Perfect Outdoor &amp; Weather proof Application<br>
                    - Smart grid application &amp; Energy efficiency<br><br><br>
                    <strong>General Features</strong><br><br>
                    - Meeting international standard IEC 61869-2 (IEC60044-1)<br>
                    - Operating current : a few hundred thousand Amps in Rogowski coils &amp; 6000Amps in integrating circuit<br>
                    - Water Proof IP67 &amp; UV protective : Weather resistive capability RoHS compliant</p>
            </div>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>1. Metering Grade Flexible Rogowski Coils</h2>
            <div class="od_spl_imgBox">
                <p>Typical Positioning Error Diagram</p>
                <img src="../img/Rogowski_Coils/typicalpositioningerror.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
            <p>(Low Positioning Error &amp; LV, MV Energy Measurement)</p>
        </div>
        <div class="tqp_srs_wrap">
            <div id="tqp_srs_wrap" class="tqp_srs_box srs_bx_01 cf">
                <div class="tqp_srs_txt">
                    <div class="srs_txt_title src_title_01 cf">
                        <h4>Drawing</h4>
                        <span></span>
                    </div>
                    <div class="srs_txt_p srs_txt_01">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus suscipit ab odio. Dolorem consequatur minus est temporibus libero perferendis quis veniam? Quae consectetur labore animi reprehenderit. Qui et dignissimos, ipsa.</p>
                    </div>
                </div>
                <div class="tqp_srs_img srs_img_01">
                    <img src="../img/Rogowski_Coils/Electrical-Properties2-graph-.png" alt="Electrical Properties-Drawing">
                </div>
            </div>
        </div>
        <div class="od_spl_title tt_w_l">
            <span></span>
            <h2>Electrical Properties<br>(IP Rating : IP67)</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore nihil excepturi vitae doloribus, nostrum ratione nesciunt, totam porro distinctio esse voluptates iusto sed perspiciatis commodi accusantium voluptatem doloremque.</p>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>2. High Frequency Monitoring Rogowski Coils</h2>
            <div class="od_spl_imgBox">
                <p>Frequency Vs. Loss (-3dB) Diagram</p>
                <img src="../img/Rogowski_Coils/frequencybandwidth.jpg" alt="frequencybandwidth">
            </div>
            <p>(Up to 1MHz Measurement &amp; Arc Fault Detection)</p>
        </div>
        <div class="tqp_srs_wrap">
            <div id="tqp_srs_wrap" class="tqp_srs_box srs_bx_01 cf">
                <div class="tqp_srs_txt">
                    <div class="srs_txt_title src_title_01 cf">
                        <h4>Drawing</h4>
                        <span></span>
                    </div>
                    <div class="srs_txt_p srs_txt_01">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus suscipit ab odio. Dolorem consequatur minus est temporibus libero perferendis quis veniam? Quae consectetur labore animi reprehenderit. Qui et dignissimos, ipsa.</p>
                    </div>
                </div>
                <div class="tqp_srs_img srs_img_01">
                    <img src="../img/Rogowski_Coils/RuggedizedSplit_draw.jpg" alt="RuggedizedSplit-Drawing">
                </div>
            </div>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>Ruggedized Split Type Rogowski Coil Sensors</h2>
            <div class="od_spl_imgBox">
                <p>Typical Positioning Error Diagram</p>
                <img src="../img/Rogowski_Coils/ruggedizedsplittype_02.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
            <div class="od_spl_imgBox">
                <img src="../img/Rogowski_Coils/XGNY0120055169.jpg" alt="Outdoor Split-Core CT Sensors">
            </div>
        </div>
        <div class="tqp_srs_wrap">
            <div id="tqp_srs_wrap" class="tqp_srs_box srs_bx_01 cf">
                <div class="tqp_srs_txt">
                    <div class="srs_txt_title src_title_01 cf">
                        <h4>Drawing</h4>
                        <span></span>
                    </div>
                    <div class="srs_txt_p srs_txt_01">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus suscipit ab odio. Dolorem consequatur minus est temporibus libero perferendis quis veniam? Quae consectetur labore animi reprehenderit. Qui et dignissimos, ipsa.</p>
                    </div>
                </div>
                <div class="tqp_srs_img srs_img_01">
                    <img src="../img/Rogowski_Coils/RuggedizedSplit_draw.jpg" alt="Electrical Properties-Drawing">
                </div>
            </div>
        </div>
        <div class="od_spl_title tt_w_l">
            <span></span>
            <h2>Electrical Properties<br>(IP Rating : IP67)</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore nihil excepturi vitae doloribus, nostrum ratione nesciunt, totam porro distinctio esse voluptates iusto sed perspiciatis commodi accusantium voluptatem doloremque.</p>
        </div>
        <div class="od_spl_title">
            <span></span>
            <h2>Integrator</h2>
            <div style="margin-top: 80px;">
                <p><strong>Features</strong><br><br>
                    - Wide Range Supply Voltage<br>
                    - Max Output Voltage 1.3Vac rms @1,000A, 60Hz<br>
                    - fMinimal Circuit Noise &amp; Excellent Accuracy</p>
            </div>
        </div>
        <div id="faq" class="od_spl_title tt_w_l tt_w_02">
            <span></span>
            <h2>FAQ</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, aut, quidem! Fugit debitis, eos ad sapiente consequuntur doloribus, laudantium, dolor incidunt iusto nisi repellendus distinctio quis? Commodi explicabo, labore suscipit.</p>
        </div>
        <div class="pp_as_ask_wrap">
            <nav class="pp_as_ask_box">
                <h3>Lorem ipsum</h3>
                <ul>
                    <li>
                        <a href="">Lorem ipsum <span class="css-arrow"></span></a>
                        <nav class="pp_as_sub">
                            <ul>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                            </ul>
                        </nav>
                    </li>
                    <li>
                        <a href="">Lorem ipsum <span class="css-arrow"></span></a>
                        <nav class="pp_as_sub">
                            <ul>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                            </ul>
                        </nav>
                    </li>
                    <li>
                        <a href="">Lorem ipsum <span class="css-arrow"></span></a>
                        <nav class="pp_as_sub">
                            <ul>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                            </ul>
                        </nav>
                    </li>
                    <li>
                        <a href="">Lorem ipsum <span class="css-arrow"></span></a>
                        <nav class="pp_as_sub">
                            <ul>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                            </ul>
                        </nav>
                    </li>
                    <li>
                        <a href="">Lorem ipsum <span class="css-arrow"></span></a>
                        <nav class="pp_as_sub">
                            <ul>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                            </ul>
                        </nav>
                    </li>
                    <li>
                        <a href="">Lorem ipsum <span class="css-arrow"></span></a>
                        <nav class="pp_as_sub">
                            <ul>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                                <li><a href="">Lorem ipsum dolor sit amet</a></li>
                            </ul>
                        </nav>
                    </li>
                </ul>
            </nav>
        </div>
        -->

    </container>
    <!-- //container -->
    <!-- footer -->
    <?php include("../inc/footer.php") ?>
    <!-- //footer -->
    <?php include("../inc/btn-up.php") ?>
</body>

</html>
